[project]
name = "justsynthesizing"
version = "0.1.0"
description = "automatic meta-analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.49.0",
    "dotenv>=0.9.9",
    "ruff>=0.9.10",
]
